[ESIMD]Test correctness of type conversion fix
intel/llvm-test-suite pull request #1170
Opened 2022-08-23 05:48 UTC by fineg74

Complementary compiler PR: https://github.com/intel/llvm/pull/6627

2022-08-23 13:00 UTC, v-klochkov commented
/verify with https://github.com/intel/llvm/pull/6627

2022-08-23 13:01 UTC, v-klochkov commented on SYCL/ESIMD/regression/double_conversion_test.cpp
> +//==--- double_conversion_test.cpp - DPC++ ESIMD on-device test ---------==//
Generally speaking, the suffix "_test" is redundant because almost all of those files in 'regression' filder are tests.

2022-08-23 13:12 UTC, v-klochkov reviewed
Looks good to me. I have only few non-blocking comments.

2022-08-23 13:12 UTC, v-klochkov commented on SYCL/ESIMD/regression/double_conversion_test.cpp
> +#include <ios>
is this include really needed? <ios>

2022-08-23 13:12 UTC, v-klochkov commented on SYCL/ESIMD/regression/double_conversion_test.cpp
> +          cgh.single_task<struct kernel>([=]() SYCL_ESIMD_KERNEL {
```suggestion
          cgh.single_task([=]() SYCL_ESIMD_KERNEL {
```

2022-08-23 13:12 UTC, v-klochkov commented on SYCL/ESIMD/regression/double_conversion_test.cpp
> +            source.copy_from(in, 0);
```suggestion
            source.copy_from(in);
```

2022-08-23 13:12 UTC, v-klochkov commented on SYCL/ESIMD/regression/double_conversion_test.cpp
> +            destination.copy_to(out, 0);
```suggestion
            destination.copy_to(out);
```

2022-08-23 13:12 UTC, v-klochkov commented on SYCL/ESIMD/regression/double_conversion_test.cpp
> +    sycl::buffer<unsigned int, 1> buffer_out(&output, range);
Not a requirement: as soon as the test is 'double_conversion', it may be nice to test 'signed int' as well.

2022-08-23 13:12 UTC, v-klochkov commented on SYCL/ESIMD/regression/double_conversion_test.cpp
> +int test(sycl::queue queue, double testValue) {
Accordingly to clang naming/format rules 'testValue' would be a good name for a function: testValue().
The vars and types start with capital letter, i.e.: 'TestValue'.

2022-08-23 15:41 UTC, fineg74 commented
/verify with https://github.com/intel/llvm/pull/6627

2022-08-30 20:45 UTC, fineg74 commented on SYCL/ESIMD/regression/double_conversion_test.cpp
> +    sycl::buffer<unsigned int, 1> buffer_out(&output, range);
Added some tests for basic test fir signed int

2022-08-30 23:08 UTC, v-klochkov commented
@fineg74 - please fix one more lang-format issue

2022-08-30 23:34 UTC, v-klochkov submitted a review, later dismissed

2022-08-31 02:29 UTC, fineg74 commented
The test fails with error: LLVM ERROR: GenX execution width and GRF crossing legalization failed for: <  %1 = fptoui <1 x double> %call2.i.i.i.i.esimd.i.i to <1 x i32>>: 'double' data type is not supported by this target <TGLLP> 
Not related to the test

2022-08-31 19:22 UTC, v-klochkov approved these changes, later dismissed

2022-08-31 19:29 UTC, v-klochkov requested changes
Please add 'aspect-fp64' to 'REQUIRES' section.

2022-09-01 01:40 UTC, v-klochkov approved these changes

2022-09-09 18:07 UTC, fineg74 commented
@v-klochkov could you please merge the test

2022-09-10 05:39 UTC, merged