[SYCL] Test for set_final_data(..) method
intel/llvm-test-suite pull request #122
Opened 2021-01-27 09:07 UTC by maximdimakov

Signed-off-by: mdimakov <maxim.dimakov@intel.com>

2021-01-29 12:50 UTC, s-kanaev reviewed
Looks good.
Though, should other types be tested here as well to ensure that there is no failure?

2021-01-29 12:50 UTC, s-kanaev commented on SYCL/Basic/buffer/buffer-set_final_data.cpp
> +}
Lacks `return 0;`

2021-01-29 12:51 UTC, s-kanaev commented
Also, there're tests for `set_final_data` in https://github.com/intel/llvm-test-suite/blob/intel/SYCL/Basic/buffer/buffer.cpp.
I believe, this test can be added there.

2021-01-29 13:14 UTC, vladimirlaz requested changes

2021-01-29 13:14 UTC, vladimirlaz commented on SYCL/Basic/buffer/buffer-set_final_data.cpp
> +      assert(false);
can you write some message and return 1 to be more user friendly?

2021-01-29 14:23 UTC, maximdimakov commented
@s-kanaev The test was moved to the buffer.cpp. It was extracted for int and double types. 
@vladimirlaz  Assert message was added

2021-02-03 05:12 UTC, vladimirlaz approved these changes

2021-02-03 05:12 UTC, merged