[SYCL] Test for local/image accessor constructors with/without proper…
intel/llvm-test-suite pull request #132
Opened 2021-02-02 13:01 UTC by maximdimakov

The test for the PR https://github.com/intel/llvm/pull/3129

Signed-off-by: mdimakov <maxim.dimakov@intel.com>

2021-02-03 07:29 UTC, s-kanaev approved these changes, later dismissed

2021-02-04 06:27 UTC, vladimirlaz requested changes

2021-02-04 06:27 UTC, vladimirlaz commented on SYCL/Basic/accessor/accessor.cpp
> +  {
Images are not supported on FPGA device.

Please add compile time guard to avoid JITing/running on accelerator device.

2021-02-04 15:42 UTC, vladimirlaz approved these changes

2021-02-04 15:43 UTC, merged