[SYCL] E2E test fot interop_task with Level-Zero using get_mem()
intel/llvm-test-suite pull request #168
Opened 2021-03-04 23:37 UTC by smaslov-intel

Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

2021-03-09 07:42 UTC, vladimirlaz commented
@againull  could you please fix the issue SYCL :: Plugin/interop-level-zero-interop-task-mem.cpp?

2021-03-09 16:24 UTC, smaslov-intel commented
@vladimirlaz , what is the compiler used in this E2E testing? The compiler fix was merged long ago, but it still looks like the fail is because of not using the right compiler.

2021-03-09 16:25 UTC, vladimirlaz commented
the latest available nightly from intel/llvm. @hanzhan1, @tfzhu could you please check and confirm, that the latest nightly is used?

2021-03-09 17:02 UTC, smaslov-intel commented
I cannot reproduce it with ToT:
```
$ "env" "SYCL_BE=PI_LEVEL_ZERO" "env" "SYCL_DEVICE_FILTER=level_zero:gpu" ./a.out

WARNING: The legacy environment variables SYCL_BE and SYCL_DEVICE_TYPE are deprecated. Please use SYCL_DEVICE_FILTER instead. For details, please refer to https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md

zeContextGetStatus = 0
Memory type = 1
```

2021-03-10 01:14 UTC, hanzhan1 commented
According to the log, pre-ci-linux used latest nightly version b1e1de06fdf8b9fa9b536e731f888bb6cd4f82be of date stamp 20210309_160000.

2021-03-10 05:17 UTC, vladimirlaz commented on SYCL/Plugin/interop-level-zero-interop-task-mem.cpp
> +// RUN: env SYCL_BE=PI_LEVEL_ZERO %GPU_RUN_PLACEHOLDER %t.out
```suggestion
// RUN: %GPU_RUN_PLACEHOLDER %t.out
```

2021-03-16 06:47 UTC, vladimirlaz requested changes

2021-03-16 06:47 UTC, vladimirlaz commented on SYCL/Plugin/interop-level-zero-interop-task-mem.cpp
> +  sycl_queue.submit([&](cl::sycl::handler &cgh) {
it is better to add try/catch wrapper to catch all possible exceptions and process them properly.
see example in https://github.com/intel/llvm-test-suite/blob/intel/SYCL/ESIMD/reduction.cpp#L50-L75

2021-03-16 06:47 UTC, vladimirlaz commented on SYCL/Plugin/interop-level-zero-interop-task-mem.cpp
> +
Can you add some data check instead of crash-check?

2021-03-16 06:47 UTC, vladimirlaz commented on SYCL/Plugin/interop-level-zero-interop-task-mem.cpp
> +  });
may be it is reasonable to have wait() here to make sure that  task will be finished before object destructions start?

2021-03-16 16:08 UTC, smaslov-intel commented
@vladimirlaz : the test is taken as is from a customer. Adding waits/catches/etc may cause completely different behavior so I don't think we need to beatify the tests.

2021-03-16 17:12 UTC, vladimirlaz commented
> @vladimirlaz : the test is taken as is from a customer. Adding waits/catches/etc may cause completely different behavior so I don't think we need to beatify the tests.

we need to be sure that the test is stable enough to use in regular testing. It should not be submitted if it is flaky or fails on some platforms.

2021-03-16 17:18 UTC, smaslov-intel commented
I agree, we should not add flaky tests for sure. Are you seeing flaky behavior in the test? The only fail that I see currently is stable:
```

[2021-03-16T05:55:48.918Z] ******************** TEST 'SYCL :: Plugin/interop-level-zero-interop-task-mem.cpp' FAILED ********************
[2021-03-16T05:55:48.918Z] Script:
[2021-03-16T05:55:48.918Z] --
[2021-03-16T05:55:48.918Z] : 'RUN: at line 2';    /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/bin/clang++     -fsycl -fsycl-targets=spir64-unknown-unknown-sycldevice  -lze_loader  -I/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/include/sycl/.. /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm-test-suite/SYCL/Plugin/interop-level-zero-interop-task-mem.cpp -o /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out
[2021-03-16T05:55:48.918Z] : 'RUN: at line 3';    env SYCL_DEVICE_FILTER=level_zero:gpu  /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out
[2021-03-16T05:55:48.918Z] --
[2021-03-16T05:55:48.918Z] Exit Code: -6
[2021-03-16T05:55:48.918Z] 
[2021-03-16T05:55:48.918Z] Command Output (stdout):
[2021-03-16T05:55:48.918Z] --
[2021-03-16T05:55:48.918Z] $ ":" "RUN: at line 2"
[2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
[2021-03-16T05:55:48.918Z] $ "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/bin/clang++" "-fsycl" "-fsycl-targets=spir64-unknown-unknown-sycldevice" "-lze_loader" "-I/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/include/sycl/.." "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm-test-suite/SYCL/Plugin/interop-level-zero-interop-task-mem.cpp" "-o" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out"
[2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
[2021-03-16T05:55:48.918Z] $ ":" "RUN: at line 3"
[2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
[2021-03-16T05:55:48.918Z] $ "env" "SYCL_DEVICE_FILTER=level_zero:gpu" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out"
[2021-03-16T05:55:48.918Z] # command output:
[2021-03-16T05:55:48.918Z] zeContextGetStatus = 0
[2021-03-16T05:55:48.918Z] 
[2021-03-16T05:55:48.918Z] # command stderr:
[2021-03-16T05:55:48.918Z] terminate called after throwing an instance of 'char const*'
[2021-03-16T05:55:48.918Z] 
[2021-03-16T05:55:48.918Z] error: command failed with exit status: -6
```
BUT I cannot reproduce it locally. Any suggestions?

2021-03-16 18:02 UTC, vladimirlaz commented
> I agree, we should not add flaky tests for sure. Are you seeing flaky behavior in the test? The only fail that I see currently is stable:
> 
> ```
> 
> [2021-03-16T05:55:48.918Z] ******************** TEST 'SYCL :: Plugin/interop-level-zero-interop-task-mem.cpp' FAILED ********************
> [2021-03-16T05:55:48.918Z] Script:
> [2021-03-16T05:55:48.918Z] --
> [2021-03-16T05:55:48.918Z] : 'RUN: at line 2';    /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/bin/clang++     -fsycl -fsycl-targets=spir64-unknown-unknown-sycldevice  -lze_loader  -I/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/include/sycl/.. /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm-test-suite/SYCL/Plugin/interop-level-zero-interop-task-mem.cpp -o /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out
> [2021-03-16T05:55:48.918Z] : 'RUN: at line 3';    env SYCL_DEVICE_FILTER=level_zero:gpu  /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out
> [2021-03-16T05:55:48.918Z] --
> [2021-03-16T05:55:48.918Z] Exit Code: -6
> [2021-03-16T05:55:48.918Z] 
> [2021-03-16T05:55:48.918Z] Command Output (stdout):
> [2021-03-16T05:55:48.918Z] --
> [2021-03-16T05:55:48.918Z] $ ":" "RUN: at line 2"
> [2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
> [2021-03-16T05:55:48.918Z] $ "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/bin/clang++" "-fsycl" "-fsycl-targets=spir64-unknown-unknown-sycldevice" "-lze_loader" "-I/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/include/sycl/.." "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm-test-suite/SYCL/Plugin/interop-level-zero-interop-task-mem.cpp" "-o" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out"
> [2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
> [2021-03-16T05:55:48.918Z] $ ":" "RUN: at line 3"
> [2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
> [2021-03-16T05:55:48.918Z] $ "env" "SYCL_DEVICE_FILTER=level_zero:gpu" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out"
> [2021-03-16T05:55:48.918Z] # command output:
> [2021-03-16T05:55:48.918Z] zeContextGetStatus = 0
> [2021-03-16T05:55:48.918Z] 
> [2021-03-16T05:55:48.918Z] # command stderr:
> [2021-03-16T05:55:48.918Z] terminate called after throwing an instance of 'char const*'
> [2021-03-16T05:55:48.918Z] 
> [2021-03-16T05:55:48.918Z] error: command failed with exit status: -6
> ```
> 
> BUT I cannot reproduce it locally. Any suggestions?



> I agree, we should not add flaky tests for sure. Are you seeing flaky behavior in the test? The only fail that I see currently is stable:
> 
> ```
> 
> [2021-03-16T05:55:48.918Z] ******************** TEST 'SYCL :: Plugin/interop-level-zero-interop-task-mem.cpp' FAILED ********************
> [2021-03-16T05:55:48.918Z] Script:
> [2021-03-16T05:55:48.918Z] --
> [2021-03-16T05:55:48.918Z] : 'RUN: at line 2';    /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/bin/clang++     -fsycl -fsycl-targets=spir64-unknown-unknown-sycldevice  -lze_loader  -I/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/include/sycl/.. /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm-test-suite/SYCL/Plugin/interop-level-zero-interop-task-mem.cpp -o /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out
> [2021-03-16T05:55:48.918Z] : 'RUN: at line 3';    env SYCL_DEVICE_FILTER=level_zero:gpu  /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out
> [2021-03-16T05:55:48.918Z] --
> [2021-03-16T05:55:48.918Z] Exit Code: -6
> [2021-03-16T05:55:48.918Z] 
> [2021-03-16T05:55:48.918Z] Command Output (stdout):
> [2021-03-16T05:55:48.918Z] --
> [2021-03-16T05:55:48.918Z] $ ":" "RUN: at line 2"
> [2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
> [2021-03-16T05:55:48.918Z] $ "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/bin/clang++" "-fsycl" "-fsycl-targets=spir64-unknown-unknown-sycldevice" "-lze_loader" "-I/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm.obj/include/sycl/.." "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/llvm-test-suite/SYCL/Plugin/interop-level-zero-interop-task-mem.cpp" "-o" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out"
> [2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
> [2021-03-16T05:55:48.918Z] $ ":" "RUN: at line 3"
> [2021-03-16T05:55:48.918Z] note: command had no output on stdout or stderr
> [2021-03-16T05:55:48.918Z] $ "env" "SYCL_DEVICE_FILTER=level_zero:gpu" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI/LLVM-Test-Suite-Lin/build/SYCL/Plugin/Output/interop-level-zero-interop-task-mem.cpp.tmp.out"
> [2021-03-16T05:55:48.918Z] # command output:
> [2021-03-16T05:55:48.918Z] zeContextGetStatus = 0
> [2021-03-16T05:55:48.918Z] 
> [2021-03-16T05:55:48.918Z] # command stderr:
> [2021-03-16T05:55:48.918Z] terminate called after throwing an instance of 'char const*'
> [2021-03-16T05:55:48.918Z] 
> [2021-03-16T05:55:48.918Z] error: command failed with exit status: -6
> ```
> 
> BUT I cannot reproduce it locally. Any suggestions?

According to logs it looks like char* string was thrown. Adding try/catch wrapper does not affect the code but helps to analyze failures.

2021-03-26 12:22 UTC, bader commented
@smaslov-intel, do you have updates for this PR?

2021-03-26 20:30 UTC, smaslov-intel commented on SYCL/Plugin/interop-level-zero-interop-task-mem.cpp
> +// Test for Level Zero interop_task
```suggestion
// Test for Level Zero interop_task.
```

2021-05-17 08:14 UTC, vladimirlaz commented
@smaslov-intel, Is this PR still needed?

2021-05-17 19:44 UTC, smaslov-intel commented
> @smaslov-intel, Is this PR still needed?

Yes. I can't reproduce the reported fail locally. How to restart the Jenkins testing?

2021-05-18 05:08 UTC, vladimirlaz commented
@smaslov-intel, I have restarted testing.

2021-05-18 05:09 UTC, vladimirlaz approved these changes, later dismissed

2021-05-19 00:42 UTC, smaslov-intel commented
> [2021-05-19T00:20:56.729Z] New failures found: ['SYCL::Basic/half_type.cpp', 'SYCL::Basic/reqd_work_group_size.cpp', 'SYCL::Functor/kernel_functor.cpp', 'SYCL::Plugin/interop-level-zero-interop-task-mem.cpp', 'SYCL::Reduction/reduction_queue_parallel_for.cpp', 'SYCL::Reduction/reduction_nd_s0_rw.cpp', 'SYCL::USM/memset.cpp']

@vladimirlaz : I have no clue how to proceed with this.
1) The test I am adding passes locally: interop-level-zero-interop-task-mem.cpp
2) Six other tests are showing as new fails, although I didn't touch them.

Any idea?

2021-05-19 13:57 UTC, vladimirlaz commented
The same tests are failing for other PRs.

2021-05-19 13:57 UTC, merged

2021-05-19 15:00 UTC, smaslov-intel commented
> The same tests are failing for other PRs.

Does it mean they are real fails that need to be analyzed/fixed?
Why are they showing as "new failures"?

2021-05-19 15:04 UTC, bader commented
Please, keep `0` failing tests.

2021-05-20 05:58 UTC, vladimirlaz commented
This is environment issue which is under analysis by tools guys.