[SYCL] E2E test to retain PI events until they have signaled
intel/llvm-test-suite pull request #180
Opened 2021-03-12 04:10 UTC by smaslov-intel

Covers the change in https://github.com/intel/llvm/pull/3350
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

2021-03-12 17:50 UTC, bso-intel approved these changes, later dismissed
LGTM

2021-03-12 17:50 UTC, bso-intel commented on SYCL/Plugin/retain_events.cpp
> +        sycl::queue Q { C , D, async_sycl_error };//, sycl::property::queue::enable_profiling() };
```suggestion
        sycl::queue Q { C , D, async_sycl_error };
```

2021-03-16 05:25 UTC, vladimirlaz commented
@smaslov-intel, could you please fix clang-format issue?

2021-03-16 05:25 UTC, vladimirlaz requested changes
@smaslov-intel, could you please fix clang-format issue?

2021-04-06 14:54 UTC, vladimirlaz approved these changes

2021-04-06 15:11 UTC, merged

2022-03-14 15:37 UTC, bader commented on SYCL/Plugin/retain_events.cpp
> +
@smaslov-intel, @againull, shouldn't we set SYCL_PI_LEVEL_ZERO_TRACK_INDIRECT_ACCESS_MEMORY or wait for all kernels to complete before freeing USM memory to make this test valid?

2022-03-14 15:37 UTC, bader commented on SYCL/Plugin/retain_events.cpp
> +
@alexbatashev FYI.