[SYCL] Remove -std=c++14 from tests as new SYCL 2020 requires C++17
intel/llvm-test-suite pull request #202
Opened 2021-03-26 18:00 UTC by dm-vodopyanov

This patch removes -std=c++14 from SYCL tests because some of the SYCL
2020 features require C++17 features and syntax

2021-03-26 19:55 UTC, DenisBakhvalov approved these changes, later dismissed

2021-03-27 18:09 UTC, kbobrovs submitted a review, later dismissed

2021-03-29 10:52 UTC, AlexeySachkov submitted a review, later dismissed

2021-03-29 11:01 UTC, dm-vodopyanov commented
Failures in Jenkins/pre-ci-linux are not related to this patch:
```
[2021-03-26T19:54:56.078Z] [proxychains] DLL init: proxychains-ng 4.14-git-34-gfa9644d
```
```
[2021-03-26T19:54:56.078Z] Abort was called at 87 line in file:
[2021-03-26T19:54:56.078Z] ../neo/shared/source/os_interface/linux/drm_buffer_object.cpp
```

2021-03-30 13:05 UTC, dm-vodopyanov commented
Failures in **Jenkins/pre-ci-windows** is not related to the changes in the patch. They can be flaky. With previous run of Jenkins/pre-ci-windows, test `regression/kernel_unnamed.cpp` failed, now - `Sampler/unnormalized-clampedge-nearest.cpp`.
@DenisBakhvalov , @kbobrovs and @AlexeySachkov , can you please re-approve?

2021-03-30 13:11 UTC, AlexeySachkov approved these changes, later dismissed

2021-03-30 15:39 UTC, DenisBakhvalov submitted a review, later dismissed

2021-03-30 15:43 UTC, dm-vodopyanov commented
@vladimirlaz , @bader , can you please merge this PR?

2021-03-30 15:55 UTC, bader commented
> Failures in **Jenkins/pre-ci-windows** is not related to the changes in the patch. They can be flaky. With previous run of Jenkins/pre-ci-windows, test `regression/kernel_unnamed.cpp` failed, now - `Sampler/unnormalized-clampedge-nearest.cpp`.
> @DenisBakhvalov , @kbobrovs and @AlexeySachkov , can you please re-approve?

Please, address pre-commit checks failure to unblock the merge. 
Even though the failure is not related to the patch, you still have to pass all checks. 
If you are not able to fix it, you can file an issue to someone else and disable the test in pre-commit validation.

2021-03-30 16:15 UTC, DenisBakhvalov commented
Opened https://github.com/intel/llvm-test-suite/issues/204 for SYCL/Sampler tests.

2021-03-30 23:14 UTC, kbobrovs approved these changes, later dismissed
LGTM

2021-03-31 06:01 UTC, vladimirlaz requested changes
Could you please revert changes in Sampler tests:
@cperkinsintel implemented some WA there:
 https://github.com/intel/llvm-test-suite/pull/207
 https://github.com/intel/llvm-test-suite/pull/196

2021-03-31 09:34 UTC, dm-vodopyanov commented
Didn't revert Sampler/normalized-clamp-nearest.cpp because there were no fixes for this test.

2021-03-31 11:10 UTC, vladimirlaz approved these changes

2021-03-31 11:11 UTC, merged