[SYCL] Apply post-commit comments for the documentation
intel/llvm-test-suite pull request #25
Opened 2020-09-15 07:39 UTC by vladimirlaz

2020-09-16 00:10 UTC, pvchupin requested changes

2020-09-16 00:10 UTC, pvchupin commented on CONTRIBUTING.md
> +Exceptions license ([LICENSE.txt](llvm/LICENSE.TXT)) to ensure our ability to
Broken link. Please update to correct upstream license.

2020-09-16 00:10 UTC, pvchupin commented on README.md
> +LLVM test suite Repository
Should it be header in md format?

2020-09-16 00:10 UTC, pvchupin commented on README.md
> +  [DPC++ Documentation](https://intel.github.io/llvm-docs/)
This is not subproject of llvm-test-suite project. You can refer as some related project.

2020-09-16 00:10 UTC, pvchupin commented on README.md
> +\*Other names and brands may be claimed as the property of others.
There should be stars added above to "LLVM".

2020-09-18 05:52 UTC, vladimirlaz commented
@pvchupin, @andykaylor  could you please have a look and approve/comment?

2020-09-18 06:20 UTC, pvchupin approved these changes, later dismissed
One edit. Otherwise look good.

2020-09-18 06:20 UTC, pvchupin commented on CONTRIBUTING.md
> +This project is licensed under the terms of the Apache License v2.0 with LLVM*
```suggestion
This project is licensed under the terms of the Apache License v2.0 with LLVM
```

2020-09-18 11:32 UTC, merged