[SCYL][ROCM] Support for ROCm backend
intel/llvm-test-suite pull request #348
Opened 2021-07-08 15:15 UTC by AidanBeltonS

Added support for targeting ROCm backend
Added new flag for -mcpu needed with sycl_triple for ROCm
Minor changes to some tests to for rocm
Updated readme to reflect the changed flags

Results from AMD GPU
Unsupported        :  99
Passed             : 183
Expectedly Failed  :   3
Failed             : 245
Unexpectedly Passed:   1

2021-07-09 06:51 UTC, vladimirlaz requested changes

2021-07-09 06:51 UTC, vladimirlaz commented on SYCL/Plugin/sycl-ls-gpu-rocm.cpp
> +// REQUIRES: gpu, rocm
```suggestion
// REQUIRES: gpu, rocm, sycl-ls
```

2021-07-09 06:51 UTC, vladimirlaz commented on SYCL/Plugin/sycl-ls-gpu-sycl-be.cpp
> +// REQUIRES: gpu, cuda, rocm, opencl
```suggestion
// REQUIRES: gpu, cuda, rocm, opencl, sycl-ls
```

2021-07-09 06:51 UTC, vladimirlaz commented on SYCL/Plugin/sycl-ls-gpu-sycl-be.cpp
> +// CHECK-BUILTIN-GPU-ROCM: gpu_selector(){{.*}}GPU : ROCM
According to https://rocmdocs.amd.com/en/latest/ is should be ROCm not ROCM

2021-07-09 06:51 UTC, vladimirlaz commented on SYCL/README.md
> + - **ROCm** - for ROCm backend;
rocm
```suggestion
 - **rocm** - for ROCm backend;
```
we use all-small here

2021-07-09 06:51 UTC, vladimirlaz commented on SYCL/README.md
> + ***MCPU*** Please not, flag must be set for when using ROCm triple.
It look slike misprinted sentence

2021-07-09 09:41 UTC, AidanBeltonS commented on SYCL/Plugin/sycl-ls-gpu-rocm.cpp
> +// REQUIRES: gpu, rocm
All changes have been implemented.
clang format has been run

2021-07-09 09:55 UTC, vladimirlaz submitted a review, later dismissed
LGTM

2021-07-14 10:56 UTC, vladimirlaz approved these changes

2021-07-15 12:12 UTC, AidanBeltonS commented
Is it possible to find out what aspect has caused the pre-ci-windows test to fail?

2021-07-15 13:20 UTC, vladimirlaz commented
The fallures on Windows are unrelated to the changes.

2021-07-15 13:20 UTC, merged

2021-07-15 13:23 UTC, vladimirlaz commented
> Is it possible to find out what aspect has caused the pre-ci-windows test to fail?

The windows failures have been addressed in https://github.com/intel/llvm-test-suite/pull/364.