[SYCL][ESIMD] Add ESIMD tests on constants specialization.
intel/llvm-test-suite pull request #35
Opened 2020-10-15 10:40 UTC by davoroni

2020-10-15 14:22 UTC, davoroni commented
I made “private/davoroni-esimd-spec-const” branch, merged changes into it, and run CI with it http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/539/pipeline/289

These are results of PI_OpenCL (+2 new esind tests)

[2020-10-15T13:57:12.310Z] PASS: SYCL :: ESIMD/histogram_256_slm_spec.cpp (51 of 108)
...
[2020-10-15T13:57:23.534Z] PASS: SYCL :: ESIMD/mandelbrot/mandelbrot_spec.cpp (57 of 108)
...
[2020-10-15T13:58:31.418Z]   Unsupported      :  8
[2020-10-15T13:58:31.418Z]   Passed           : 97
[2020-10-15T13:58:31.418Z]   Expectedly Failed:  3

Should I create new PR from “private/davoroni-esimd-spec-const” or we can continue with this PR?

2020-10-15 15:28 UTC, kbobrovs requested changes

2020-10-15 15:28 UTC, kbobrovs commented on SYCL/ESIMD/mandelbrot/mandelbrot_spec.cpp
> +  // SIMT_BEGIN(16, lane) {
```suggestion
```

2020-10-15 15:28 UTC, kbobrovs commented on SYCL/ESIMD/mandelbrot/mandelbrot_spec.cpp
> +  } // SIMT_END
```suggestion
  }
```

2020-10-15 16:01 UTC, davoroni commented on SYCL/ESIMD/mandelbrot/mandelbrot_spec.cpp
> +  // SIMT_BEGIN(16, lane) {
done

2020-10-15 16:01 UTC, davoroni commented on SYCL/ESIMD/mandelbrot/mandelbrot_spec.cpp
> +  } // SIMT_END
done

2020-10-15 16:33 UTC, kbobrovs approved these changes

2020-10-16 04:36 UTC, vladimirlaz approved these changes

2020-10-16 04:37 UTC, merged