[SYCL] Update free function queries tests
intel/llvm-test-suite pull request #350
Opened 2021-07-12 08:33 UTC by alexbatashev

Compiler changes are here: https://github.com/intel/llvm/pull/4090

2021-07-12 10:02 UTC, vladimirlaz submitted a review, later dismissed

2021-07-20 08:10 UTC, alexbatashev commented
Updated tests to be in alignment with https://github.com/intel/llvm/pull/4014

2021-08-16 05:29 UTC, vladimirlaz requested changes
@alexbatashev the relevant change was submitted to the compiler code base a while ago.
The test is still failing. Could you please fix the test?

2021-08-25 06:20 UTC, alexbatashev commented
@vladimirlaz it's passing now

2021-08-25 06:31 UTC, vladimirlaz approved these changes

2021-08-25 06:32 UTC, merged