[SYCL] Disable fallback assert in kernel bundle merge options test
intel/llvm-test-suite pull request #360
Opened 2021-07-14 06:59 UTC by s-kanaev

2021-07-14 10:53 UTC, vladimirlaz requested changes

2021-07-14 10:53 UTC, vladimirlaz commented on SYCL/KernelAndProgram/kernel-bundle-merge-options-env.cpp
> +// Fisable fallback assert here so, that build process isn't affected
```suggestion
// Disable fallback assert here so, that build process isn't affected
```

2021-07-15 05:40 UTC, v-klochkov approved these changes

2021-07-15 09:39 UTC, vladimirlaz commented
Failures on Windows happened because GPU driver uplift and unrelated to the changes in this PR.

2021-07-15 09:39 UTC, vladimirlaz approved these changes

2021-07-15 09:40 UTC, merged