[SYCL] string.h function test for libdevice
intel/llvm-test-suite pull request #371
Opened 2021-07-20 03:08 UTC by jinge90

Signed-off-by: gejin <ge.jin@intel.com>

This PR adds test for functions in <string.h> including memcpy, memset, memcmp. Once https://github.com/intel/llvm/pull/4147
is merged, this test should pass.
Thanks very much.

2021-08-06 06:25 UTC, jinge90 commented on SYCL/DeviceLib/string_test.cpp
> +        memcpy(local_acc.get_pointer(), src_acc.get_pointer(), 8);
Hi, @vzakhari 
kernel_test_memcpy_addr_space is used to test memcpy whose input pointers have different address space. Could you help review if it meets our requirement?
Thanks very much.

2021-08-06 18:29 UTC, vzakhari approved these changes, later dismissed

2021-08-09 12:18 UTC, vladimirlaz commented
@jinge90 could you please fix clang-format issues?

2021-08-16 04:15 UTC, vladimirlaz requested changes
@jinge90, could you please fix formatting issues and make sure the test is passing on all configurations?

2021-08-17 02:18 UTC, jinge90 commented
Hi, vladimirlaz
I have fixed the clang-format issue but found a lot of CUDA tests have failed. Adding a test case shouldn't impact other tests, so is there any other problem?
Thanks very much.

2021-08-17 05:40 UTC, vladimirlaz commented
> Hi, vladimirlaz
> I have fixed the clang-format issue but found a lot of CUDA tests have failed. Adding a test case shouldn't impact other tests, so is there any other problem?
> Thanks very much.
This is known issue addressed in intel/llvm#4348.

2021-08-17 05:41 UTC, vladimirlaz approved these changes

2021-08-17 16:57 UTC, vzakhari approved these changes

2021-08-20 09:33 UTC, merged