[SYCL] Add tests for new SYCL config processing
intel/llvm-test-suite pull request #412
Opened 2021-08-18 18:21 UTC by denis-kabanov

Add nine tests for new SYCL config processing.

2021-08-18 20:17 UTC, dm-vodopyanov commented on SYCL/Config/check_config_processing.cpp
> +           "Variable name is more than 256 or less than one character") ||
It's better to check for specific error message for each individual run.

2021-08-18 20:17 UTC, dm-vodopyanov commented on SYCL/Config/check_config_processing.cpp
> +          (errorMessage == "The value contains more than 256 characters or "
Need to skip comparison with the specific number during checking of error message (e.g., using regex)

2021-08-18 20:17 UTC, dm-vodopyanov commented on SYCL/Config/check_config_processing.cpp
> +           "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
Better to replace it here and above with a loop

2021-08-19 07:52 UTC, vladimirlaz requested changes
I suggest to abandon this PR because the test does not depend on BEs. It is better to have it as unittest in compiler repository.

2021-08-20 11:37 UTC, closed without merging