[SYCL] Added test for deprecated features
intel/llvm-test-suite pull request #435
Opened 2021-09-01 12:47 UTC by maximdimakov

Signed-off-by: mdimakov <maxim.dimakov@intel.com>

2021-09-02 05:19 UTC, vladimirlaz requested changes
Could you provide more details for the purpose of the test?
It is unclear what is actually tested especially because there is no check condition step.

2021-09-02 05:20 UTC, vladimirlaz commented
if a new directory is added please update .github/CODEOWNERS.

2021-09-02 07:03 UTC, maximdimakov commented
@vladimirlaz I updated the description of PR.

2021-09-02 07:31 UTC, alexbatashev commented on .github/CODEOWNERS
> +SYCL/Deprecated_features @maximdimakov @alexbatashev
```suggestion
SYCL/DeprecatedFeatures @intel/llvm-reviewers-runtime
```

2021-09-02 15:23 UTC, romanovvlad approved these changes

2021-09-06 12:40 UTC, vladimirlaz approved these changes

2021-09-06 12:55 UTC, merged