[SYCL][XPTI] Enable XPTI and XPTI Frameworks E2E tests
intel/llvm-test-suite pull request #458
Opened 2021-09-11 19:26 UTC by alexbatashev

2021-09-12 15:21 UTC, alexbatashev commented
Depends on https://github.com/intel/llvm/pull/4545

2021-09-14 06:19 UTC, vladimirlaz approved these changes

2021-09-16 06:23 UTC, vladimirlaz requested changes

2021-09-16 06:23 UTC, vladimirlaz commented on SYCL/lit.cfg.py
> +# TODO properly set XPTIFW include and runtime dirs
The change looks like a hack.
We can detect the presence of the library in Cmaake and pass this value through lit.site.cfg.py. Also, you can get proper include and other directories from CMake configuration to resolve TODO above.

2021-09-16 06:23 UTC, vladimirlaz commented on SYCL/XPTI/basic_event_collection.cpp
> +// RUN: env XPTI_TRACE_ENABLED=1 env XPTI_FRAMEWORK_DISPATCHER=%xptifw_lib env XPTI_SUBSCRIBERS=%t_collector.dll %CPU_RUN_PLACEHOLDER %t %CPU_CHECK_PLACEHOLDER
The test is running on CPU only. Is it a requirement? If so, `cpu` should be added to REQUIRES. If not we can remove CPU_RUN_PLACEHOLDERs.

As for my understanding, it should work for any BE so it is better to removed dependencies on specific device type.

2021-09-21 15:37 UTC, romanovvlad commented on SYCL/XPTI/basic_event_collection.cpp
> +// RUN: env XPTI_TRACE_ENABLED=1 env XPTI_FRAMEWORK_DISPATCHER=%xptifw_dispatcher env XPTI_SUBSCRIBERS=%t_collector.dll env SYCL_DEVICE_FILTER=opencl %t.out | FileCheck %s 2>&1
```suggestion
// RUN: env XPTI_TRACE_ENABLE=1 env XPTI_FRAMEWORK_DISPATCHER=%xptifw_dispatcher env XPTI_SUBSCRIBERS=%t_collector.dll env SYCL_DEVICE_FILTER=opencl %t.out | FileCheck %s 2>&1
```

XPTI_TRACE_ENABLE=1 ?

2021-10-11 05:42 UTC, vladimirlaz requested changes

2021-10-11 05:42 UTC, vladimirlaz commented on SYCL/lit.cfg.py
> +    config.substitutions.append(('%xptifw_includes', xptifw_includes))
Do we really need separate substitutions? Are they used separately?
if not we can merge them

2021-10-11 05:42 UTC, vladimirlaz commented on SYCL/XPTI/basic_event_collection.cpp
> +// RUN: %clangxx -fsycl -fsycl-unnamed-lambda -fsycl-targets=%sycl_triple %s -o %t.out
```suggestion
// RUN: %clangxx -fsycl %s -o %t.out
```
If options are not needed we can skip them

2021-10-11 05:42 UTC, vladimirlaz commented on SYCL/XPTI/basic_event_collection.cpp
> +// RUN: %clangxx %s -DXPTI_COLLECTOR -L%xptifw_lib -I%xptifw_includes -shared -fPIC -std=c++17 -o %t_collector.dll -lxptifw
the command line will not work is clang-cl is used (-std=c++17 and -fPIC will not work).

There ar substitutions for such a case: https://github.com/intel/llvm-test-suite/blob/intel/SYCL/lit.cfg.py#L139

2021-12-09 13:21 UTC, bader commented
@alexbatashev, please, resolve merge conflicts and apply suggestions from previous reviews.

2021-12-21 12:19 UTC, vladimirlaz submitted a review, later dismissed

2021-12-21 18:43 UTC, vladimirlaz submitted a review, later dismissed

2021-12-22 09:01 UTC, vladimirlaz approved these changes

2021-12-22 09:01 UTC, merged