Disable USM pooling tests while implementation is being changed.
intel/llvm-test-suite pull request #529
Opened 2021-10-21 15:23 UTC by rdeodhar

This change removes tests previously added for USM pooling. The pooling implementation is being changed. Once that change is completed these tests will be adjusted and reenabled.

2021-10-21 18:02 UTC, rdeodhar commented
The two unexpected passes are expected. A change planned in the intel_llvm repo will cause those tests to fail. That's why they are marked ax XFAIL now, in anticipation of the intel_llvm change.

2021-10-22 08:53 UTC, sergey-semenov submitted a review, later dismissed

2021-10-25 21:04 UTC, jbrodman submitted a review, later dismissed

2021-10-28 05:07 UTC, vladimirlaz approved these changes

2021-10-28 05:29 UTC, vladimirlaz requested changes

2021-10-28 05:29 UTC, vladimirlaz commented on SYCL/USM/usm_leak_check.cpp
> +// XFAIL: level_zero
Only SYCL :: USM/usm_pooling.cpp failed on windows (see testing in intel/llvm#4799). The current test should not be XFAILED there

2021-10-28 22:48 UTC, rdeodhar commented on SYCL/USM/usm_leak_check.cpp
> +// XFAIL: level_zero
Windows is currently **unsupported** by usm_leak_check.cpp because the ZE_DEBUG=4 feature that the test depends on does not work on Windows. See line 3 in the test. So the XFAIL takes effect on Linux only. Yet, it should do no harm on Windows.
Otherwise, please suggest a combination of UNSUPPORTED, XFAIL, REQUIRES that you think would be more appropriate.

2021-10-29 04:28 UTC, vladimirlaz commented on SYCL/USM/usm_leak_check.cpp
> +// XFAIL: level_zero
in this case, it should be ok. UNSUPORTED disables the test and XFAIL should be ignored

2021-10-29 04:28 UTC, vladimirlaz submitted a review, later dismissed

2021-10-29 16:37 UTC, rdeodhar commented
Nothing has been changed, but need re-approval from code owners.

2021-10-29 16:38 UTC, sergey-semenov submitted a review, later dismissed

2021-10-29 16:48 UTC, jbrodman submitted a review, later dismissed

2021-10-29 20:07 UTC, againull approved these changes

2021-10-29 20:10 UTC, jbrodman approved these changes

2021-10-29 23:22 UTC, againull commented
Unrelated ESIMD tests failed, merging.

2021-10-29 23:22 UTC, merged