[SYCL][CUDA] Add unit test for local arguments alignment
intel/llvm-test-suite pull request #608
Opened 2021-12-10 18:22 UTC by npmiller

This issue was solved in intel/llvm#5113, local kernel arguments have to
be aligned to the type size.

cc @romanovvlad

2021-12-12 15:51 UTC, vladimirlaz commented
/verify with intel/llvm#5113

2021-12-12 15:53 UTC, vladimirlaz approved these changes

2021-12-14 13:58 UTC, vladimirlaz approved these changes

2021-12-21 09:42 UTC, steffenlarsen approved these changes

2022-01-12 10:57 UTC, bader approved these changes

2022-02-10 08:17 UTC, vladimirlaz commented
@npmiller it looks like the test is failing on Linux (OpenCL BE). I have restarted it with the latest compiler.

2022-02-11 06:07 UTC, vladimirlaz requested changes
@npmiller could  you please fix CI issue reported for OpenCL BE.
```
[2022-02-10T07:00:45.849Z] ******************** TEST 'SYCL :: Regression/local-arg-align.cpp' FAILED ********************
[2022-02-10T07:00:45.849Z] Script:
[2022-02-10T07:00:45.849Z] --
[2022-02-10T07:00:45.849Z] : 'RUN: at line 1';    /runDir/jenkins-dir/workspace/llvm.obj/bin/clang++      -fsycl -fsycl-targets=spir64 /runDir/jenkins-dir/workspace/llvm-test-suite/SYCL/Regression/local-arg-align.cpp -o /runDir/jenkins-dir/workspace/build/SYCL/Regression/Output/local-arg-align.cpp.tmp.out
[2022-02-10T07:00:45.849Z] : 'RUN: at line 3';   env SYCL_DEVICE_FILTER=host  /runDir/jenkins-dir/workspace/build/SYCL/Regression/Output/local-arg-align.cpp.tmp.out
[2022-02-10T07:00:45.849Z] : 'RUN: at line 4';   env SYCL_DEVICE_FILTER=opencl:cpu,host  /runDir/jenkins-dir/workspace/build/SYCL/Regression/Output/local-arg-align.cpp.tmp.out
[2022-02-10T07:00:45.849Z] : 'RUN: at line 5';    env SYCL_DEVICE_FILTER=opencl:gpu,host  /runDir/jenkins-dir/workspace/build/SYCL/Regression/Output/local-arg-align.cpp.tmp.out
[2022-02-10T07:00:45.849Z] : 'RUN: at line 6';    env SYCL_DEVICE_FILTER=acc  /runDir/jenkins-dir/workspace/build/SYCL/Regression/Output/local-arg-align.cpp.tmp.out
[2022-02-10T07:00:45.849Z] --
[2022-02-10T07:00:45.849Z] Exit Code: 255
[2022-02-10T07:00:45.849Z] 
[2022-02-10T07:00:45.849Z] Command Output (stdout):
[2022-02-10T07:00:45.849Z] --
[2022-02-10T07:00:45.849Z] $ ":" "RUN: at line 1"
[2022-02-10T07:00:45.849Z] note: command had no output on stdout or stderr
[2022-02-10T07:00:45.849Z] $ "/runDir/jenkins-dir/workspace/llvm.obj/bin/clang++" "-fsycl" "-fsycl-targets=spir64" "/runDir/jenkins-dir/workspace/llvm-test-suite/SYCL/Regression/local-arg-align.cpp" "-o" "/runDir/jenkins-dir/workspace/build/SYCL/Regression/Output/local-arg-align.cpp.tmp.out"
[2022-02-10T07:00:45.849Z] note: command had no output on stdout or stderr
[2022-02-10T07:00:45.849Z] $ ":" "RUN: at line 3"
[2022-02-10T07:00:45.849Z] note: command had no output on stdout or stderr
[2022-02-10T07:00:45.849Z] $ "env" "SYCL_DEVICE_FILTER=host" "/runDir/jenkins-dir/workspace/build/SYCL/Regression/Output/local-arg-align.cpp.tmp.out"
[2022-02-10T07:00:45.849Z] # command output:
[2022-02-10T07:00:45.849Z] Error: incorrect alignment for argument b, required alignment: 32, address: 0x1af3730
[2022-02-10T07:00:45.849Z] 
[2022-02-10T07:00:45.849Z] error: command failed with exit status: 255
[2022-02-10T07:00:45.849Z] 
[2022-02-10T07:00:45.849Z] --
[2022-02-10T07:00:45.849Z] 
[2022-02-10T07:00:45.849Z] ********************
```

2022-02-11 10:24 UTC, npmiller commented
Oh that's interesting, do you have more details on what OpenCL runtime and device is being used in the CI?

I've had another look through the test, and I can't really see anything wrong with it, I think this is likely a problem in the OpenCL runtime, or potentially how the SPIR-V binaries are generated, I'll try to see if I can track it down a bit further.

2022-02-11 10:56 UTC, npmiller commented
I'm actually able to reproduce this with the Nvidia OpenCL so I reckon this is likely what the CI also uses.

2022-02-11 16:12 UTC, npmiller commented
Okay, so I have tracked this down, it's actually not an issue with OpenCL at all, it's a host problem.

Local accessors for host are allocated as `std::vector<char>`, so they might be misaligned:
* https://github.com/intel/llvm/blob/sycl/sycl/include/CL/sycl/detail/accessor_impl.hpp#L180

Which is exactly what happens in this test. Replacing this with an aligned allocation on `MElemSize` I get the test to pass, I'm looking into submitting a patch for this, however it does break the ABI which is not ideal.

2022-03-01 14:08 UTC, npmiller commented
The failing test should be fixed now that https://github.com/intel/llvm/pull/5554 was merged

2022-03-01 14:21 UTC, vladimirlaz approved these changes

2022-03-01 14:22 UTC, vladimirlaz commented
will wait till next compiler nightly to ensure that the test will pass with it before merge

2022-03-01 14:30 UTC, steffenlarsen approved these changes

2022-03-04 08:26 UTC, merged