[ESIMD] Add a test exercising 2D workitem coordinates.
intel/llvm-test-suite pull request #73
Opened 2020-12-17 02:48 UTC by kbobrovs

Signed-off-by: Konstantin S Bobrovsky <konstantin.s.bobrovsky@intel.com>

2020-12-17 07:07 UTC, kychendev approved these changes, later dismissed

2020-12-18 18:25 UTC, DenisBakhvalov requested changes

2020-12-18 18:25 UTC, DenisBakhvalov commented on SYCL/ESIMD/vadd_2d_acc.cpp
> +  }
Please add try/catch blocks.

2020-12-24 00:29 UTC, kbobrovs commented on SYCL/ESIMD/vadd_2d_acc.cpp
> +  }
done

2020-12-26 03:04 UTC, DenisBakhvalov approved these changes

2021-01-15 05:48 UTC, vladimirlaz commented
@kychendev is it OK to merge the PR? The tests are passing and there are no unresolved comments.

2021-01-15 06:39 UTC, kychendev commented
> @kychendev is it OK to merge the PR? The tests are passing and there are no unresolved comments.

Yes, I didn't notice my last review was dismissed after last update. Approving now.

2021-01-15 06:40 UTC, kychendev approved these changes

2021-01-15 07:24 UTC, merged