[SYCL][WIP][DO NOT MERGE] test new complex support by group_algorithms
intel/llvm-test-suite pull request #767
Opened 2022-01-25 21:25 UTC by cperkinsintel

updating tests to reflect new support of std::complex by joint_reduce and reduce_over_group

Signed-off-by: Chris Perkins <chris.perkins@intel.com>

2022-01-27 19:17 UTC, cperkinsintel commented
/verify https://github.com/intel/llvm/pull/5394

2022-01-28 16:21 UTC, Pennycook requested changes

2022-01-28 16:21 UTC, Pennycook commented on SYCL/GroupAlgorithm/exclusive_scan_sycl2020.cpp
> +  std::array<std::complex<float>, N> output_cf;
Should we test `float` and `double`?

2022-02-01 04:40 UTC, cperkinsintel commented on SYCL/GroupAlgorithm/exclusive_scan_sycl2020.cpp
> +  std::array<std::complex<float>, N> output_cf;
done

2022-02-01 15:28 UTC, Pennycook approved these changes, later dismissed

2022-02-01 17:50 UTC, cperkinsintel commented
/verify with https://github.com/intel/llvm/pull/5394

2022-02-02 15:52 UTC, steffenlarsen reviewed
Tests look good, but I fear it could cause failures on devices without `aspect::fp64`. Do we test on any such devices?

2022-02-02 16:50 UTC, cperkinsintel commented
@steffenlarsen  - I added protection to check for aspect::fp64 before testing std::complex<double>

2022-02-02 17:16 UTC, steffenlarsen commented
> @steffenlarsen - I added protection to check for aspect::fp64 before testing std::complex

You have! But the problem is that the kernel using fp64 operations may be bundled together with the other kernels. This means when the test kernels are built they may include this kernel and fail.

2022-02-04 17:17 UTC, cperkinsintel commented
/verify with https://github.com/intel/llvm/pull/5394

2022-02-08 05:44 UTC, vladimirlaz submitted a review, later dismissed

2022-02-08 05:47 UTC, vladimirlaz commented
> > @steffenlarsen - I added protection to check for aspect::fp64 before testing std::complex
> 
> You have! But the problem is that the kernel using fp64 operations may be bundled together with the other kernels. This means when the test kernels are built they may include this kernel and fail.

The potential fixes for the situation may be:
 - move fp64 code to separate test;
 - use -fsycl-device-code-split==per_kernel option for building test app.

2022-02-08 21:21 UTC, cperkinsintel commented
I believe this is ready for merge.

2022-02-09 06:08 UTC, vladimirlaz commented
> I believe this is ready for merge.


don't we want to add  -fsycl-device-code-split=per_kernel to avoid potential failures on devices that do not support fp64?

2022-02-09 18:07 UTC, steffenlarsen submitted a review, later dismissed
LGTM! Thanks for adding the split. 😄

2022-02-09 19:07 UTC, steffenlarsen approved these changes

2022-02-10 05:55 UTC, vladimirlaz approved these changes

2022-02-10 05:56 UTC, merged