[SYCL][FPGA][NFC] Change AOT tool requirement for FPGA emulator
intel/llvm-test-suite pull request #807
Opened 2022-02-07 12:51 UTC by mlychkov

'opencl-aot' is used as backend compiler for FPGA emulator device instead of
'aoc' tool now.
Change AOT compilation tool requirement for tests that should be executed on
FPGA emulator device.

Signed-off-by: Mikhail Lychkov <mikhail.lychkov@intel.com>

2022-02-07 12:53 UTC, alexbatashev approved these changes, later dismissed
Thanks!

2022-02-07 13:14 UTC, mlychkov commented
@alexbatashev Strictly speaking, there are no tests for FPGA hardware target in this suite, because additional command line option should be specified for SYCL compiler to build a binary for that target.
So, **aoc** might be completely removed from llvm-test-suite if there is no plans for adding FPGA HW tests.

2022-02-07 14:05 UTC, AlexeySachkov submitted a review, later dismissed

2022-02-09 07:32 UTC, vladimirlaz requested changes
can we also remove aoc from https://github.com/intel/llvm-test-suite/blob/intel/SYCL/lit.cfg.py#L399?

2022-02-09 11:41 UTC, vladimirlaz approved these changes

2022-02-09 12:12 UTC, mlychkov commented
@vladimirlaz I updated PR's description. Could you please use it as commit message when you'll be merging this patch?

2022-02-09 17:21 UTC, AlexeySachkov approved these changes

2022-02-09 18:18 UTC, alexbatashev approved these changes

2022-02-10 05:27 UTC, merged