[ESIMD] Add regression test for unused load.
intel/llvm-test-suite pull request #87
Opened 2020-12-31 00:28 UTC by kbobrovs

Signed-off-by: Konstantin S Bobrovsky <konstantin.s.bobrovsky@intel.com>

2021-01-03 07:52 UTC, vladimirlaz commented on SYCL/ESIMD/regression/unused_load.cpp
> +// REQUIRES: linux && gpu
The https://github.com/intel/llvm-test-suite/pull/77/files pr just enables ESIMD tets on Windows. So you can add this test test on Windows as well.

2021-01-03 07:54 UTC, vladimirlaz commented
Could you please add links to tests. You can replace IDs of the jobs in th elinks below with the ones you have run:
http://llvm-ci.intel.com:8080/job/SYCL_CI/job/intel/job/Lin/job/LLVM_Test_Suite/1022/display/redirect
http://llvm-ci.intel.com:8080/job/SYCL_CI/job/intel/job/Lin/job/LLVM_Test_Suite_CUDA/956/display/redirect
http://llvm-ci.intel.com:8080/job/SYCL_CI/job/intel/job/Win/job/Test_Suite/231/display/redirect

2021-01-03 07:55 UTC, vladimirlaz requested changes
please address the comments

2021-01-13 06:07 UTC, kbobrovs commented
@vladimirlaz - please review again, sorry for delay. Windows still can't be enabled due to driver issue.
Also, I did not understand this comment:
> Could you please add links to tests. You can replace IDs of the jobs in the links below with the ones you have run:

2021-01-13 06:36 UTC, vladimirlaz commented
> @vladimirlaz - please review again, sorry for delay. Windows still can't be enabled due to driver issue.
> Also, I did not understand this comment:
> 
> > Could you please add links to tests. You can replace IDs of the jobs in the links below with the ones you have run:

You should run the tests in CI and put links to test jobs here. Please use format of links provided in my comment.

2021-01-13 19:34 UTC, kbobrovs commented
> You should run the tests in CI and put links to test jobs here.

how to do that? /summary:run?

2021-01-15 05:50 UTC, vladimirlaz approved these changes

2021-01-15 05:50 UTC, merged