[SYCL] Fix XFAIL rules
intel/llvm-test-suite pull request #879
Opened 2022-03-02 12:02 UTC by vladimirlaz

Floating-point atomics are not available only on CPU and FPGA emulator RTs. Replace opencl with cpu,acc in XFAIL rule

2022-03-02 12:15 UTC, sergey-semenov approved these changes, later dismissed

2022-03-07 08:42 UTC, t4c1 requested changes
Is reducing the test coverage to a single type per operation necessary to reach the required testing time? If it is, it might make sense to put tests for other types behind a macro like you did with deprecated tests from `ext` namespace.

2022-03-07 08:42 UTC, t4c1 commented on SYCL/AtomicRef/add.h
> +  if (std::find(scopes.begin(), scopes.end(), memory_scope::system) !=
```suggestion
  if (std::find(scopes.begin(), scopes.end(), memory_scope::work_group) !=
```
Just noticed this is actually wrong.

2022-03-07 08:42 UTC, t4c1 commented on SYCL/AtomicRef/add.h
> +  if (std::find(scopes.begin(), scopes.end(), memory_scope::system) !=
```suggestion
  if (std::find(scopes.begin(), scopes.end(), memory_scope::sub_group) !=
```

2022-03-07 08:42 UTC, t4c1 commented on SYCL/AtomicRef/compare_exchange_generic_local.cpp
> +// RUN: %clangxx -fsycl -fsycl-unnamed-lambda -fsycl-targets=%sycl_triple %s -o %t.out -Xsycl-target-backend=nvptx64-nvidia-cuda --cuda-gpu-arch=sm_70
This change is inconsistent with what is done in other files.

2022-03-07 08:42 UTC, t4c1 commented on SYCL/AtomicRef/sub.h
> +  if (std::find(scopes.begin(), scopes.end(), memory_scope::system) !=
```suggestion
  if (std::find(scopes.begin(), scopes.end(), memory_scope::sub_group) !=

```

2022-03-07 08:42 UTC, t4c1 commented on SYCL/AtomicRef/xor_local.cpp
>  // (no macro for a group) are: 32 bit, relaxed and device.
You are changing this behavior, so this comment can be removed (from all cpp files).

2022-03-08 07:41 UTC, t4c1 approved these changes
LGTM

2022-03-10 05:05 UTC, vladimirlaz commented
@sergey-semenov could you please have a look/approve?

2022-03-10 05:27 UTC, vladimirlaz commented
@yanfeng3721 could you please have a look?

2022-03-10 05:44 UTC, yanfeng3721 commented
> @yanfeng3721 could you please have a look?

LGTM.

2022-03-10 09:32 UTC, merged