[SYCL] [L0] [PI] Corrections to interop tests to ensure batching behavior
intel/llvm-test-suite pull request #948
Opened 2022-03-24 21:49 UTC by rdeodhar

Some interop tests depend on assumptions about the plugin behavior with regard to commandlist and event usage. The expectations can be met by setting env vars that control batching and device-only events usage.

2022-03-25 20:37 UTC, rdeodhar commented
/verify with intel/llvm-test-suite#948

2022-03-25 20:38 UTC, rdeodhar commented
/verify with intel/llvm#5833

2022-03-25 21:21 UTC, smaslov-intel commented on SYCL/Plugin/interop-level-zero-interop-task-mem.cpp
> +// RUN: env SYCL_BE=PI_LEVEL_ZERO SYCL_PI_LEVEL_ZERO_DEVICE_SCOPE_EVENTS=2 SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 %GPU_RUN_PLACEHOLDER %t.out
I don't see any check of traces in this test, so it should run with any env settings

2022-03-25 21:22 UTC, smaslov-intel commented on SYCL/Plugin/interop-level-zero-keep-ownership.cpp
> +// RUN: env SYCL_BE=PI_LEVEL_ZERO SYCL_PI_LEVEL_ZERO_DEVICE_SCOPE_EVENTS=2 SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 %GPU_RUN_PLACEHOLDER %t.out
I don't see any check of traces in this test, so it should run with any env settings

2022-03-25 21:22 UTC, smaslov-intel requested changes

2022-03-25 21:22 UTC, smaslov-intel commented on SYCL/Plugin/interop-level-zero-thread.cpp
> +// RUN: env SYCL_PI_LEVEL_ZERO_DEVICE_SCOPE_EVENTS=2 SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0 %BE_RUN_PLACEHOLDER %t.out
same here

2022-04-12 19:48 UTC, rdeodhar commented
These tests fail if immediate commandlists are used in the L0 plugin.
The tests will need to be revisited when/if use of immediate commandlists is made the default.

2022-04-12 19:48 UTC, closed without merging